# Use MongoDB image
FROM mongo:6.0

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=root_username
ENV MONGO_INITDB_ROOT_PASSWORD=root_password

# Expose MongoDB port
EXPOSE 27017

# Start MongoDB server
CMD ["mongod"]
